### ISSUE TITLE
[BUG] Pure market making | Account has insufficient balance for requested action

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1791] opened 2020-05-20 21:03 UTC
**Describe the bug**
Placing an order at the same time by two separate hummingbot instances can cause the the order to skip the order placement.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
Please note that the image below is the configuration of two separate instances. 
One instance  running RLC-ETH while another instance running ZIL-ETH pair
![image](https://user-images.githubusercontent.com/53868268/82496335-8c7fc600-9aba-11ea-8e8b-ea1df5740e4a.png)

2. Start the bot 
Please note that the order refresh time is set to 1. This config will increase the chance of the error to occur.

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/82496969-8807dd00-9abb-11ea-9521-9e12007c2605.png)

**Release version**
// 0.27.0
Running two hummingbot instances running RLC-ETH and ZIL-ETH pair

**Attachments**
Error logs shows the following:
```
Traceback (most recent call last):
  File "binance_market.pyx", line 879, in hummingbot.market.binance.binance_market.BinanceMarket.create_order
  File "binance_market.pyx", line 254, in query_api
  File "binance_market.pyx", line 266, in hummingbot.market.binance.binance_market.BinanceMarket.query_api
  File "binance_market.pyx", line 256, in hummingbot.market.binance.binance_market.BinanceMarket.query_api
  File "/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1149, in create_order
    return self._post('order', True, data=params)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 210, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 176, in _request
    return self._handle_response(response)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 200, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
2020-05-20 16:44:11,411 - 10 - hummingbot.market.binance.binance_market - WARNING - APIError(code=-2010): Account has insufficient balance for requested action.

```

[ZIL-ETH logs.log](https://github.com/CoinAlpha/hummingbot/files/4659329/ZIL-ETH.logs.log)
[RLC-ETH logs.log](https://github.com/CoinAlpha/hummingbot/files/4659330/RLC-ETH.logs.log)

A similar error was posted on https://github.com/CoinAlpha/hummingbot/issues/601
It seems that the issue resurfaced

**Comment by rennel-tabing** [comment] 2020-05-21 14:07
another user reported an error of 
`"binance.exceptions.BinanceAPIException: APIError(code=-2010): Duplicate order sent."`
which could be related to the issue above.
He is using similar pairs with different order amount across his multiple instances.

**Comment by dennisocana** [comment] 2020-10-20 05:44
Closing since the edge case behavior or error cannot be reproduced using the steps provided.

**Closed by dennisocana** 2020-10-20 05:44 UTC
Labels: bug
