### ISSUE TITLE
Pure MM - Unable to start when inventory price is not configured 

### ISSUE THREAD

**Issue by developeralexandre** [CoinAlpha/hummingbot#2947] opened 2021-02-11 19:16 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
Error 
![image](https://user-images.githubusercontent.com/68089896/107686236-b77efb00-6c83-11eb-8811-5256e8c37eca.png)

It is stopping bot to place orders.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

I have tested on binary (windows) and using Docker (windows).

It happens when I try to use INVENTORY_PRICE at price TYPE

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
Binance and PURE Market Maker at XRP-BRL pair
2. Start the bot using this command: ...
...
Start
**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/68089896/107686579-2ceacb80-6c84-11eb-83f3-666e8449dd60.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
![image](https://user-images.githubusercontent.com/68089896/107686632-3f650500-6c84-11eb-8e05-22f983ed1340.png)

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5967876/logs_hummingbot.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Karalhos#8536

After that I stop My bot and change price type to MID_PRICE and the erros stoped.

**Comment by RC-13** [comment] 2021-02-12 02:27
@developeralexandre The error above is an expected behavior when `inventory_price` is not configured after setting the price_type to `inventory_cost`.  Kindly try configuring your inventory_price and test it again, let us know if the same issue will persist. Here's the reference for this feature: PR:#2513 and ticket:#2314

**Comment by rapcmia** [comment] 2021-02-18 02:07
Sent follow up to user via discord regarding this issue, waiting for response.

**Comment by dennisocana** [comment] 2021-02-18 03:19
As discussed, this happens because of a misconfiguration issue. @keithbaum will look into this on how to handle in the client.

**Comment by dennisocana** [comment] 2021-04-01 01:54
This is addressed in version 0.38

**Closed by dennisocana** 2021-04-01 01:54 UTC
