### ISSUE TITLE
[BUG] Volume trades from Oct 10 - 13 are missing 

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#918] opened 2019-10-15 09:47 UTC
**Describe the bug**
Bounty performance from Oct 10 - 13 are not updated, on logs it is very clear that there are orders being filled on these days. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27669951/66819542-c0699a80-ef71-11e9-82c8-385bc7edb7ee.png)

I already advised the user to update hummingbot to its latest stable version, though i'm not sure if it has something to do with the version. 

**Version**
0.13.0

**Logs**
[gruberx_logs.log](https://github.com/CoinAlpha/hummingbot/files/3728500/gruberx_logs.log)

**Optional: your discord username:** gruberx
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by yzhang1994** [comment] 2019-10-16 19:08
@znerol19619 This is caused by a bug in our client. The bug is fixed in the development branch and will be released on Monday. However, in order to recover the user's lost trade data, we'll have to collect his read-only API keys on Binance.

**Comment by znerol19619** [comment] 2019-10-25 06:22
Confirmed fix, will now close this bug report

**Closed** 2019-10-25 06:23 UTC
Labels: bug
