### ISSUE TITLE
[BUG] dev-0.33.0 binance_perpetual balance limit not working

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2572] opened 2020-11-07 13:47 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
Setting a balance limit on binance_perpetual gives an error of invalid command arguments
![image](https://user-images.githubusercontent.com/63117227/98442866-ccd60d80-2107-11eb-920b-7aaec74e5ee1.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
dev-0.33.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!

**Comment by mifeng** [comment] 2020-11-16 14:42
@vic-en to look into whether limits can be set via API

**Comment by vic-en** [comment] 2021-02-08 15:40
Solution to be decided after scoping top derivative exchanges.
This is not a bug as the balance-limit was disabled for derivatives on purpose because of how they handle balances.

**Comment by RC-13** [comment] 2021-02-09 10:35
Closing this ticket for now, and will be part of the future enhancement

**Closed by RC-13** 2021-02-09 10:35 UTC
Labels: binance futures, bug
