### ISSUE TITLE
Binance_US - BuyOrderCompletedEvent not issued on last fill

### ISSUE THREAD

**Issue by marcap02** [CoinAlpha/hummingbot#3085] opened 2021-03-16 00:20 UTC
**Describe the bug**
When running the pure_market_making strategy on Binance_US on buy events the BuyOrderCompletedEvent is missing. This is a problem for strategy scripts which are doing actions on this event. 

My custom activities on the BuyOrderCompletedEvent are not being executed and there is not the typical log line "Maker buy order has been completely filled." in the log either. 

This only seems to appear with buy orders. I did observe it today multiple times. 

**Steps To Reproduce**
Using BNB-USDT on Binance_US. Order_amount 2 (I haven't seen these failing split order with a smaller order_amount.
<img width="382" alt="image" src="https://user-images.githubusercontent.com/57306710/111236519-08ef1280-85c1-11eb-8a0a-3482439511d3.png">

Logged sequence:
<Start>
2021-03-15 23:10:03,107 - 1 - hummingbot.script.script_iterator - INFO - received: StrategyParameter {'name': 'bid_spread', 'attr': '_bid_spread', 'updated_value': Decimal('0.0001')}
2021-03-15 23:10:03,107 - 1 - hummingbot.script.script_iterator - INFO - received: StrategyParameter {'name': 'ask_spread', 'attr': '_ask_spread', 'updated_value': Decimal('0.25')}
2021-03-15 23:10:03,107 - 1 - hummingbot.script.script_iterator - INFO - received: StrategyParameter {'name': 'order_refresh_tolerance_pct', 'attr': '_order_refresh_tolerance_pct', 'updated_value': 0}
...
2021-03-15 23:10:16,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?2025. [clock=2021-03-15 23:10:16+00:00]
2021-03-15 23:10:16,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?2216. [clock=2021-03-15 23:10:16+00:00]
2021-03-15 23:10:16,217 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-X?-?2025.
2021-03-15 23:10:16,239 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849816.0, "order_id": "x-X?-?2025", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:10:16,717 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-X?-?2216.
2021-03-15 23:10:16,743 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849816.0, "order_id": "x-X?-?2216", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:10:17,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Creating 1 bid orders at (Size, Price): ['2 BNB, 256.3802 USDT']
2021-03-15 23:10:17,002 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Creating 1 ask orders at (Size, Price): ['1.41 BNB, 320.7359 USDT']
2021-03-15 23:10:17,226 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-X?-?2148 for 2.00000000 BNB-USDT.
2021-03-15 23:10:17,250 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849817.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "2.00000000", "price": "256.38020000", "order_id": "x-X?-?2148", "exchange_order_id": "65029358", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_us"}
2021-03-15 23:10:17,727 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER SELL order x-X?-?2373 for 1.41000000 BNB-USDT.
2021-03-15 23:10:17,748 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849817.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "1.41000000", "price": "320.73590000", "order_id": "x-X?-?2373", "exchange_order_id": "65029359", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "binance_us"}
...
<repeat order creation every 30 seconds as set in strategy>
...
2021-03-15 23:10:48,128 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-X?-?1219 for 2.00000000 BNB-USDT.
2021-03-15 23:10:48,149 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849848.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "2.00000000", "price": "256.38460000", "order_id": "x-X?-?1219", "exchange_order_id": "65029503", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_us"}
...
2021-03-15 23:11:06,490 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Maker buy order of 1.74000000 BNB filled. [clock=2021-03-15 23:11:06+00:00]
2021-03-15 23:11:06,528 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849866.418, "order_id": "x-X?-?1219", "trading_pair": "BNB-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "256.38460000", "amount": "1.74000000", "trade_fee": ["0", [["BNB", "0.00130500"]]], "exchange_trade_id": 1018782, "leverage": 1, "position": "NILL", "event_name": "OrderFilledEvent", "event_source": "binance_us"}
2021-03-15 23:11:09,597 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - The market order x-X?-?1219 was already filled or order was not submitted by hummingbot.Ignoring trade filled event of exchange trade id 1018782 in user stream.
...
2021-03-15 23:11:18,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?1219. [clock=2021-03-15 23:11:18+00:00]
2021-03-15 23:11:18,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?1443. [clock=2021-03-15 23:11:18+00:00]
2021-03-15 23:11:18,139 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849878.0, "order_id": "x-X?-?1219", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:11:18,621 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-X?-?1443.
2021-03-15 23:11:18,650 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849878.0, "order_id": "x-X?-?1443", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:11:19,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Creating 1 ask orders at (Size, Price): ['2 BNB, 320.4062 USDT']
2021-03-15 23:11:19,124 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER SELL order x-X?-?1785 for 2.00000000 BNB-USDT.
2021-03-15 23:11:19,143 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849879.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "2.00000000", "price": "320.40620000", "order_id": "x-X?-?1785", "exchange_order_id": "65029623", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "binance_us"}
...
2021-03-15 23:11:49,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?1785. [clock=2021-03-15 23:11:49+00:00]
2021-03-15 23:11:49,126 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-X?-?1785.
2021-03-15 23:11:49,149 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849909.0, "order_id": "x-X?-?1785", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:11:50,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Creating 1 ask orders at (Size, Price): ['2 BNB, 319.9109 USDT']
2021-03-15 23:11:50,115 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER SELL order x-X?-?1291 for 2.00000000 BNB-USDT.
2021-03-15 23:11:50,143 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849910.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "2.00000000", "price": "319.91090000", "order_id": "x-X?-?1291", "exchange_order_id": "65029698", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "binance_us"}
2021-03-15 23:12:01,125 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Maker buy order of 0.26000000 BNB filled. [clock=2021-03-15 23:12:01+00:00]
2021-03-15 23:12:01,168 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849869535, "order_id": "x-X?-?1219", "trading_pair": "BNB-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "256.38460000", "amount": "0.26000000", "trade_fee": ["0", [["BNB", "0.00019500"]]], "exchange_trade_id": 1018783, "leverage": 1, "position": "NILL", "event_name": "OrderFilledEvent", "event_source": "binance_us"}
2021-03-15 23:12:01,168 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Recreating missing trade in TradeFill: {'symbol': 'BNBUSDT', 'id': 1018783, 'orderId': 65029503, 'orderListId': -1, 'price': '256.38460000', 'qty': '0.26000000', 'quoteQty': '66.65999600', 'commission': '0.00019500', 'commissionAsset': 'BNB', 'time': 1615849869535, 'isBuyer': True, 'isMaker':
True, 'isBestMatch': True}
2021-03-15 23:12:20,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Cancelling the limit order x-X?-?1291. [clock=2021-03-15 23:12:20+00:00]
2021-03-15 23:12:20,125 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-X?-?1291.
2021-03-15 23:12:20,148 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849940.0, "order_id": "x-X?-?1291", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_us"}
2021-03-15 23:12:21,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Creating 1 ask orders at (Size, Price): ['2 BNB, 320.3521 USDT']
2021-03-15 23:12:21,129 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER SELL order x-X?-?1580 for 2.00000000 BNB-USDT.
2021-03-15 23:12:21,150 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1615849941.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BNB-USDT", "amount": "2.00000000", "price": "320.35210000", "order_id": "x-X?-?1580", "exchange_order_id": "65029877", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source"
: "binance_us"}

**Screenshots**
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/57306710/111237616-7b60f200-85c3-11eb-8f4e-cc05c77a0b46.png">

**Release version**
Version: 0.36.0

**Discord username:** MarkusM#2638

**Comment by glenntomas** [comment] 2021-03-16 01:15
Hi! That is caused by slippage. Slippage refers to the difference between the expected price of a trade and the price at which the trade is executed and can occur at any time but is most prevalent during periods of higher volatility when market orders are used by other traders.

**Comment by rxlxrxsx** [comment] 2021-03-16 01:23
Closing as inquiry has already addressed on Discord

**Comment by marcap02** [comment] 2021-03-16 01:38
@rxlxrxsx slippage causes that there’s no BuyOrderCompletedEvent being generated? Sorry but I red in the source code that this event has always to be generated with the last filled order event. I thought we discussed on Discord that slippage caused the orders to be split.

**Comment by rxlxrxsx** [comment] 2021-03-16 02:01
When your order has been filled completely it should show the BuyOrderCompletedEvent, even if it's partially filled at first but gets filled completely afterwards. If it's only partially filled and the whole order size doesn't get filled during the time it's open, the order completed event will not show. Can you send your complete log file when you encountered this behavior? I was looking into the one you posted here but I think it's incomplete. Re-opening this ticket to further check.

**Comment by marcap02** [comment] 2021-03-16 02:54
Thanks for re-opening and apologies I should have communicated better that I had a two staged question/issue. Why wouldn't the order be complete if order_amout = 2 and I got the two orders which add up to 2 below filled?

2021-03-15 23:11:06,490 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Maker buy order of 1.74000000 BNB filled. [clock=2021-03-15 23:11:06+00:00]
2021-03-15 23:12:01,125 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BNB-USDT) Maker buy order of 0.26000000 BNB filled. [clock=2021-03-15 23:12:01+00:00]

Do I have to shadow anything in the log file such as the order_id or is that all good? That was the main reason why I didn't attach the full file.

**Comment by rxlxrxsx** [comment] 2021-03-16 03:09
Yes that's okay, we actually require users to send the full log file so we can better troubleshoot the issue and see how the bot behaves.

**Comment by RC-13** [comment] 2021-09-30 01:03
Closing the ticket, I've inspected our binance test bot which has been running for more than 2days and all bid orders has complete event. Do open the ticket if issue arise in the future.

**Closed by RC-13** 2021-09-30 01:03 UTC
Labels: P3, bug
