### ISSUE TITLE
[BUG] RadarRelay - Limit orders require an expiration timestamp 'expiration_ts'

### ISSUE THREAD

**Issue by gonchs** [CoinAlpha/hummingbot#568] opened 2019-07-19 05:57 UTC
**Describe the bug**
Running a pure market making strategy on Radar Relay is currently not possible.

Setting `limit_order_min_expiration` is not accepted.

```
Traceback (most recent call last):
  File "/hummingbot/client/config/config_helpers.py", line 162, in load_yml_into_cm
    raise ValueError(f"Cannot find corresponding config to key {key}.")
ValueError: Cannot find corresponding config to key limit_order_min_expiration.
2019-07-17 06:19:24,529 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (USDC-DAI) Creating limit bid orders for   Bids (Size,Price) to be placed at: ['10.0 USDC @  0.9998544539059193 DAI'] [clock=2019-07-17 06:19:24+00:00]
2019-07-17 06:19:24,531 - hummingbot.market.radar_relay.radar_relay_market - ERROR - Limit orders require an expiration timestamp 'expiration_ts'. Aborting.
```

**Steps To Reproduce**
1. Install the bot on OSX
2. Use these [configs](https://gist.github.com/gonchs/c55dfc04ceb0833900a53e57d3ca2445)
3. Run the bot

**Release version**
0.10.1

Bug bounty ETH address: 0xC39F1316fF2CaBC45CCb52f236e56947354845FA

**Comment by martinkou** [comment] 2019-07-19 06:25
This is caused by a missing `kwarg` passing in the current strategy base class.

Should be fixed in https://github.com/CoinAlpha/hummingbot/pull/567

**Comment by mifeng** [comment] 2019-07-23 00:48
Fixed in `development` branch

**Comment by mifeng** [comment] 2019-07-23 00:49
@gonchs This is eligible for our bug bounty program, so we will send you 0.1 ETH

**Closed by mifeng** 2019-07-23 00:48 UTC
Labels: bug

**Comment by moraliang** [comment] 2019-07-23 00:54
@gonchs  Already sent. :)
