### ISSUE TITLE
[BUG] Error when importing config files with uppercase characters

### ISSUE THREAD

**Issue by hrkuipers** [CoinAlpha/hummingbot#1999] opened 2020-07-07 10:41 UTC
**Describe the bug**
Version: 0.28.1, Centos
On a fresh start-up of the docker, when trying to load a saved strategy, the import fails and humminbot becomes unresponsive if the strategy you are attempting to load has capitals in it's file name. The workaround is to rename the the strategy to a lower-case filename but it should work with upper case file names as well

**Steps To Reproduce**
_As example I have a file named VET-btc-puremm-01.yml_
- fresh start-up
- command: import import VET-btc-puremm-01.yml
- responds in log window: 10:34:02 - async_utils - Unhandled error in background task: [Errno 2] No such file or directory: 'conf/vet-btc-puremm-01.yml' (See log file for stack trace dump)

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1035431/86768964-a9faf600-c04e-11ea-8971-b44b6b9a61c7.png)

**Release version**
0.28.1

**Log**

2020-07-07 10:34:02,432 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory: 'conf/vet-btc-puremm-01.yml'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/import_command.py", line 37, in import_config_file
    strategy = update_strategy_config_map_from_file(strategy_path)
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 217, in update_strategy_config_map_from_file
    strategy = strategy_name_from_file(yml_path)
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 199, in strategy_name_from_file
    with open(file_path) as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/vet-btc-puremm-01.yml'

**Optional: your discord username:**
hrkuipers#0407

**Comment by PtrckM** [comment] 2020-07-07 12:27
Unable to replicate the issue tried both docker build (_centos/ubuntu)_, source build and thru binary installer on windows, on version **0.28.1** and **dev-0.29.0** (docker/source)


- docker ubuntu
![image](https://user-images.githubusercontent.com/54516858/86779303-fd406900-c08d-11ea-8aa8-a97f8b95239d.png)

- docker centos
![image](https://user-images.githubusercontent.com/54516858/86779363-0c271b80-c08e-11ea-9b29-fc04336bd4d9.png)

**Comment by hrkuipers** [comment] 2020-07-07 14:31
Hi Patrick,

It is a persistent issue on my side. If you would like to set-up a screen
sharing session, e.g. through zoom, I'm more than happy to do that. I'm
also willing to give you access to the linux machine directly but in that
case I will remove my API keys first.


Kind regards,


Hans


Hans Kuipers

**Comment by rxlxrxsx** [comment] 2020-07-08 09:08
Getting the same behavior on my bot (docker, version-0.28.1, ubuntu). The current workaround is to rename the config file to lower case characters
![image](https://user-images.githubusercontent.com/64377055/86899484-a6459d00-c13c-11ea-8657-85c4626dc33e.png)
![image](https://user-images.githubusercontent.com/64377055/86899704-f15fb000-c13c-11ea-84f8-7f57732422a3.png)
![image](https://user-images.githubusercontent.com/64377055/86900108-806cc800-c13d-11ea-853d-7558e702ca8a.png)
![image](https://user-images.githubusercontent.com/64377055/86900153-924e6b00-c13d-11ea-965e-3ebba2c97c85.png)

**Comment by dennisocana** [comment] 2020-09-14 23:41
Confirmed that the bug is isolated to a docker-installed Hummingbot only and not when installed from source or via binary. Screenshots below shows importing files without issues.

From source on macOS, Linux and Windows :

![Screen Shot 2020-09-15 at 7 17 46 AM](https://user-images.githubusercontent.com/50150287/93148422-52e86000-f726-11ea-9c59-765af474efc0.png)
![image](https://user-images.githubusercontent.com/50150287/93148466-6b587a80-f726-11ea-979c-6abcd70ba193.png)
![image](https://user-images.githubusercontent.com/50150287/93148521-94790b00-f726-11ea-9d5a-b9d2e292640f.png)

Via binary on Windows :

![image](https://user-images.githubusercontent.com/50150287/93148550-ace92580-f726-11ea-8080-6316d7abe4db.png)

Error with docker in Linux :

![image](https://user-images.githubusercontent.com/50150287/93148622-df931e00-f726-11ea-9a52-a407d349dd1c.png)

**Comment by PatrickLiPM** [comment] 2020-09-14 23:42
![windows_test_results](https://user-images.githubusercontent.com/10274325/93148527-053a0c00-f6c2-11ea-82d0-d7f5dc1ebcfb.PNG)
![linux_test_results](https://user-images.githubusercontent.com/10274325/93148528-05d2a280-f6c2-11ea-8405-a0425a2d208b.png)
![mac_test_results](https://user-images.githubusercontent.com/10274325/93148534-079c6600-f6c2-11ea-9061-3201a56f1ddf.png)
This issue cannot be replicated on Window, Mac and Linux on dev-0.32.0.

However, we can replicate it on Docker, so the issue is isolated to docker installed HB, will continue investigation.

![docker_test_result](https://user-images.githubusercontent.com/10274325/93148684-737ece80-f6c2-11ea-85a9-c184f429343c.png)

**Comment by PatrickLiPM** [comment] 2020-09-16 13:10
The Docker version also works fine, and I couldn't reproduce the issue in Docker, will close the issue for now.

**Closed by PatrickLiPM** 2020-09-16 13:10 UTC
Labels: bug

**Comment by ZeroCool940711** [comment] 2020-10-01 06:50
Im facing this problem with Hummingbot when running it from source on an Ubuntu 20.04 VPS.
After I did everything to install HB on a clean Ubuntu 20.04 installation and copied my config files from my computer when I tried to import my config HB can't see the config file even tho the files are on the correct place just because it contains uppercase characters for the pair name.
Here is a screenshot showing it, on the left side you can clearly see how HB sees the config files as they are shown on the selection menu but on the right side you can see how it says on the log it can't find the file inside the config folder.
![unknown](https://user-images.githubusercontent.com/5977640/94776762-2c0d6900-0377-11eb-81bb-1a65096a308e.png)

After I renamed the config file to have lowercase only the problem was fixed and I can import the config file now. We should be able to import our config no matter if we use lower or upper case on the name of the file, some of us for clarity like to put the pair name on the filename and use upper case for it so its easy to know to what pair the file belongs to.

**Comment by Cubiant** [comment] 2020-10-06 08:50
![2020-10-06 13_52_00-ubuntu@ip-172-31-34-232_ ~](https://user-images.githubusercontent.com/16476116/95179717-a5291800-07de-11eb-9348-1873ea8efd57.jpg)
Got this error while trying to import in my config file, tried both upper and lower cases in the import command.
![2020-10-06 14_04_27-AWS - sftp___ubuntu@ec2-65-0-18-0 ap-south-1 compute amazonaws com - FileZilla P](https://user-images.githubusercontent.com/16476116/95179849-d1dd2f80-07de-11eb-93fc-bf3cc67435dd.jpg)
I did have the file in the directory, I went to discord support and @sigit2306 told me the filename needs to be in lower-case. Worked after that.
