### ISSUE TITLE
Bot unable to place order for orders paired with ADA in Kraken

### ISSUE THREAD

**Issue by jimbot-test** [CoinAlpha/hummingbot#3157] opened 2021-04-04 08:34 UTC
Pairs in Kraken are working except for ADA, tested on Binance exchange for ADA-USDT and it works both in paper trade and live. The issue occurs in Kraken for ADA trades.

Here are the configurations to reproduce the issue:
1. Strategy: pure_market_making
2. Exchange: Kraken
3. Market: ADA-USDT
4. bid_spread: 0.1
5. ask_spread: 0.1
6. order_refresh_time: 900
7. order_amount: 11
8. ping_pong: No

...

Version: 0.37.1
Environment: Docker on AWS 2 instance
![unknown (1)](https://user-images.githubusercontent.com/81898193/113503289-81fbdd00-9563-11eb-920f-5801a604b4d3.png)
![unknown](https://user-images.githubusercontent.com/81898193/113503292-832d0a00-9563-11eb-9f5d-7dcda1b19e81.png)
<img width="666" alt="Screen_Shot_2021-04-04_at_12 26 04_AM" src="https://user-images.githubusercontent.com/81898193/113503294-845e3700-9563-11eb-9aa4-dce51caeb8ee.png">

**Comment by sidmontanez** [comment] 2021-04-04 19:28
Hi, @jimbot-test I tried checking this out on my end and it works fine. Did you add a `paper balance` for ADA before you start the bot? 

![image](https://user-images.githubusercontent.com/78310937/113519443-c5376980-95be-11eb-991d-18d7dc7eb7b8.png)

**Comment by rxlxrxsx** [comment] 2021-04-04 22:48
@jimbot-test Can you try to adjust your order_amount to 25 and see if it'll place orders? Based on Kraken's [minimum order size](https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading) requirement it requires you 25 ADA to place orders on pairs related to it. Once replicated, please close the ticket. Thanks!

<img width="1423" alt="Screen Shot 2021-04-05 at 6 36 35 AM" src="https://user-images.githubusercontent.com/64377055/113523548-99c27800-95da-11eb-98f7-25de6742e2cd.png">

@sidmontanez There is an existing [bug](https://github.com/CoinAlpha/hummingbot/issues/2183) that let's you place orders below the minimum order size allowed by the exchanges.

**Comment by RC-13** [comment] 2021-04-05 04:15
Closing ticket, the reported concern is not a bug rather a misconfiguration for the order_amount.
![image](https://user-images.githubusercontent.com/57189990/113536368-8928f680-9608-11eb-8b3b-de7252d613fa.png)

**Closed by RC-13** 2021-04-05 04:15 UTC
