### ISSUE TITLE
[BUG] Kraken error running performance analysis in paper trade

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1782] opened 2020-05-19 08:41 UTC
Creating a separate ticket since the pair that was working in https://github.com/CoinAlpha/hummingbot/issues/1780 (ETH-USDT) is having an error when in paper trading mode and may not have the same cause of problem.

Error in **ETH-USDT** pair - [paper_trade_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4649175/paper_trade_eth-usdt.log)

<img width="947" alt="putty_1qI9K5oUth" src="https://user-images.githubusercontent.com/50150287/82304341-c7b4c300-99ee-11ea-8f1e-5d1ddbb3d936.png">

Did another test in a different pair - **BCH-EUR** in paper trade and no errors.

<img width="947" alt="putty_uX6qgytmiV" src="https://user-images.githubusercontent.com/50150287/82304392-d7cca280-99ee-11ea-9dbf-4ad9623ca2c3.png">

**Version** : latest 0.27.0
**Environment** : Docker in AWS EC2 instance

**Comment by mifeng** [comment] 2020-05-26 00:48
@kmcgowan2000 is this bug fixed now?

**Comment by kmcgowan2000** [comment] 2020-05-26 03:42
@mifeng not yet – will be later this week

**Comment by kmcgowan2000** [comment] 2020-06-11 17:39
this appears to be happening because starting balances only seem to include the base and quote of the first strategy that is run once the client is opened. will look into the cause of this

**Closed** 2020-06-15 16:04 UTC
Labels: bug, kraken, paper trading
