### ISSUE TITLE
[BUG] Order book snapshot errors after kill switch triggered

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1140] opened 2019-11-29 03:11 UTC
**Describe the bug**

When kill switch is triggered and the bot stops, it continues to get order book snapshots resulting to:

1. Flooding the log file with errors
2. Huge log file size
3. IP getting banned in Binance due to API requests

```
2019-11-27 02:00:00,575 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 233, in listen_for_order_book_snapshots
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 125, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for [BASEQUOTE]. HTTP status is 429.

2019-11-27 02:02:37,398 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Error getting snapshot for [BASEQUOTE]. 
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 144, in get_tracking_pairs
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair, 1000)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 125, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for [BASEQUOTE]. HTTP status is 418.
```

**Release version**

```
"branch": "development",
"commit": "59a64224020e8f598d5612a784c27c0d7fc16bf2",
"date": "2019-11-22T20:22:41Z",
```

**Attachments**

Sent message through Discord.

**Comment by mifeng** [comment] 2020-05-09 04:09
This was the start/stop bug that was fixed in #1683 

In hindsight, the description of this issue could have helped us track down the root cause!

**Closed by mifeng** 2020-05-09 04:09 UTC
Labels: bug
