### ISSUE TITLE
Refactor VWAP strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3432] opened 2021-05-24 13:10 UTC
**This requirement is still a work in progress**

# What?
The `dev_5_vwap` was first implemented as strategy creation demo for external developers and hasn't been touched in a long time. Currently the strategy isn't working properly.

The strategies must be refactored to update the code to make proper use of the current code base, but also to work as stand-alone public strategies that are public available on the `master` branch.

**Curent state of the strategy**

_VWAP_

* When creating the strategy, there is no prompt for strategy configurations
* orders aren't being created, even with `order_type` = `limit`
* the config `is_vwap` is redundant. A similar config should exist when combining both strategies on a single config file.
  * Config prompt is asked when there is a change on this config
* `percent_slippage` unclear explanation on the config prompt
* `order_percent_of_volume` unclear explanation on the config prompt

# Why?
The code of these strategies must be updated to the most recent framework of the code base.

This strategies are also widely used by traders that need to negotiate big volumes. 

Making them public available allows to demostrante different ways that hummingbot can be used by big players.

Due to it's simplicity, they are good examples for developers on how to build new strategies.

# How?
_(Describe one or more possible ways that the feature can be implemented. Ask devs about different ways the problem could be approached)_

V**WAP**

**Configurations/Variables needed:**

# Impact?
_(Describe what is the expected impact of the implementation, be it good or bad)_

# Alternatives?
_(Write down if there is any alternatives worth discussing to solve the core problem problem of the requirement)_

# References
## Research sources
VWAP

[https://empirica.io/blog/vwap-algorithm/](https://empirica.io/blog/vwap-algorithm/)

[https://blog.quantinsti.com/vwap-strategy/](https://blog.quantinsti.com/vwap-strategy/)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramkyy) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment] 2021-05-31 10:40
@phbrgnomo it was mentioned during last Friday's standup that the story https://github.com/CoinAlpha/hummingbot/issues/3431 to refactor TWAP should be completed first before working on this. In that case, we should move this to the sprint after the blocker is done.

**Comment by aarmoa** [comment] 2021-06-03 13:13
According to the description the only required changes are the configuration parameters and the texts presented to the user to describe each configuration. Is that correct?

**Comment by dennisocana** [comment] 2021-06-03 15:43
Moving to backlog, waiting for the refactor TWAP to complete.

**Comment by phbrgnomo** [comment] 2021-06-04 19:44
> According to the description the only required changes are the configuration parameters and the texts presented to the user to describe each configuration. Is that correct?

On the case of VWAP, the strategy wasn't working at all (orders not being created).

So this first refactor will be about making it actually work, and also adding more user-friendly interaction, like better configuration prompts.

**Comment by dennisocana** [comment] 2021-06-07 09:39
@phbrgnomo I'll ask the support or QA to reproduce the issue and create a Github ticket since it looks like a bug in the strategy. So we can also track the task of fixing it apart from this refactor story.

**Comment by dennisocana** [comment] 2021-06-07 10:07
Here's the Github issue https://github.com/CoinAlpha/hummingbot/issues/3528 submitted by QA.

**Closed** 2021-11-03 18:23 UTC
Labels: refactor
