### ISSUE TITLE
Paper trade mode does not report if it cannot connect to order books

### ISSUE THREAD

**Issue by miohtama** [CoinAlpha/hummingbot#2848] opened 2021-01-19 13:55 UTC
**Describe the bug**

Paper trade mode uses [real data](https://hummingbot.io/academy/quickstart/run-bot/#enable-paper-trading-mode-optional). However, in a paper trade mode, the bot can be started with non-functional exchanges connections. This leads to a usability confusion when using the paper trade mode - the user does not know if the paper trade mode is pulling in data or is crashed.

Happy to tackle this issue with a pull request if some guidance received how this should be fixed.

**Steps To Reproduce**

1. Create an arbitrate strategy
2. Make sure you do not have any exchange API keys
3. Start the bot
4. type in `status`

Expected result:

Same as live trading

<img width="400" alt="image" src="https://user-images.githubusercontent.com/49922/105043528-eda2d380-5a65-11eb-95e1-79e7d93e4973.png">

Actual result:

It says "markets ready":

<img width="567" alt="image" src="https://user-images.githubusercontent.com/49922/105043665-188d2780-5a66-11eb-8c81-7f3876a9cfb1.png">

No notice that it failed to connect to exchanges:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/49922/105043715-29d63400-5a66-11eb-9ac1-8899841bfb76.png">

Paper trade does nothing and does not guide the user to resolve the situation.

**Release version**

Development branch.

**Comment by rapcmia** [comment] 2021-01-20 05:46
Unfortunately, paper trade doesn't work with Arbitrage yet. This would normally work for Pure Market Making and Cross Market making as of the moment.

**Comment by miohtama** [comment] 2021-01-20 10:58
> Paper trade will assume that you have stable connection, and will create orders based on the current pulled information from the exchange order book and the setting you set on your strategy

Maybe this assumption should be still clarified in the user interface, as users are not aware of this assumption.

**Comment by RC-13** [comment] 2021-02-09 10:43
Closing ticket since this is not a bug

**Closed by RC-13** 2021-02-09 10:43 UTC
Labels: bug
