### ISSUE TITLE
Orders not refreshing

### ISSUE THREAD

**Issue by FahadAziz** [CoinAlpha/hummingbot#2827] opened 2021-01-10 20:31 UTC
**Describe the bug**
Im using market making perpetual, multi level orders. once an order gets filled the bot stops refreshing orders. I am using take profit feature. 

**Steps To Reproduce**
1- Set up multi level orders
2- Binance futures
3- wait for an order to get filled.
4- bot runs into an error that it cant refresh orders.
5- once the active order gets closed, bot runs with no issues.

Error message:
23:30:14 - hummingbot_cli - Unhandled error in prompt_toolkit: [WinError 10038] An operation was attempted on something that is not a socket (See log file for stack trace dump)

I am running it on Windows 10

Why this is an issue? because sometimes an order gets filled in the last second before all open orders gets refreshed. Bot will not refresh orders until active order gets closed.

Thanks

**Comment by krisj** [comment] 2021-01-10 22:05
@FahadAziz is this in Hedged or One-Way mode?
See my report on [2813](https://github.com/CoinAlpha/hummingbot/issues/2813)

According to developers this is by design. In my opinion it is wrong. I have not tested this in One-Way mode.

**Comment by vic-en** [comment] 2021-01-10 22:41
@FahadAziz Kindly include you config and log files.

**Comment by FahadAziz** [comment] 2021-01-11 05:16
@krisj I think we have the same issue

@vic-en Here you go

the error Im referring to 

`2021-01-10 23:04:09,454 - 23928 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "asyncio\events.py", line 81, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost`


Config

`########################################################
###       Perpetual market making strategy config         ###
########################################################

template_version: 3
strategy: perpetual_market_making

# derivative and token parameters.
derivative: binance_perpetual

# Token trading pair for the exchange, e.g. BTC-USDT
market: XLM-USDT

# What leverage to used
leverage: 20

# Position mode to use, hedge mode or one-way position mode.
position_mode: Hedge

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 0.5

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 0.5

# Minimum Spread
# How far away from the mid price to cancel active orders
minimum_spread: -100.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 60.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 1.0

# Size of your bid and ask order.
order_amount: 200.0

# Which position management feature to use. Trailing stop and take profit features are currently supported
position_management: Profit_taking

# long position take profit spread
long_profit_taking_spread: 1.5

# short position take profit spread
short_profit_taking_spread: 1.5

# Activation spread for trailing stop
ts_activation_spread: 5.0

# Callback rate for trailing stop
ts_callback_rate: 2.0

# OrderType to use for closing positions when using Trailing stop feature
close_position_order_type: LIMIT

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Whether to alternate between buys and sells (true/false).
ping_pong_enabled: false

# Number of levels of orders to place on each side of the order book.
order_levels: 10

# Increase or decrease size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 50.0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 20.0

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top ask (for order optimization mode).
ask_order_optimization_depth: 0.0

# The depth in base asset amount to be used for finding top bid (for order optimization mode).
bid_order_optimization_depth: 0.0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# The price source (current_market/external_market/custom_api).
price_source: current_market

# The price type (mid_price/last_price/last_own_trade_price/best_bid/best_ask).
price_type: mid_price

# An external exchange name (for external exchange pricing source).
price_source_derivative:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for custom_api pricing source).
price_source_custom_api:

#Take order if they cross order book when external price source is enabled
take_if_crossed:

# Use user provided orders to directly override the orders placed by order_amount and order_level_parameter
# This is an advanced feature and user is expected to directly edit this field in config file
# Below is an sample input, the format is a dictionary, the key is user-defined order name, the value is a list which includes buy/sell, order spread, and order amount
# order_override:
#   order_1: [buy, 0.5, 100]
#   order_2: [buy, 0.75, 200]
#   order_3: [sell, 0.1, 500]
# Please make sure there is a space between : and [
order_override:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
`

**Comment by RC-13** [comment] 2021-01-11 05:25
@FahadAziz Can you attach the whole strategy log file, you can follow the step on this link to locate your log files: https://docs.hummingbot.io/intro/support/#where-are-my-config-and-log-files

**Comment by FahadAziz** [comment] 2021-01-11 05:44
> @FahadAziz Can you attach the whole strategy log file, you can follow the step on this link to locate your log files: https://docs.hummingbot.io/intro/support/#where-are-my-config-and-log-files

Done above

**Comment by RC-13** [comment] 2021-01-13 02:55
@FahadAziz I'm going to close this ticket since it's similar to #2813 this is to avoid duplicate tickets, you can follow the existing one for updates.

**Closed** 2021-01-13 02:55 UTC
Labels: binance futures, bug
