### ISSUE TITLE
[BUG] Config fee override not working on live trades

### ISSUE THREAD

**Issue by sigit2306** [CoinAlpha/hummingbot#2078] opened 2020-07-20 10:51 UTC
**Describe the bug**
Updating maker fee and taker fee in `conf_fee_overrides.yml` doesn't affect `fee_percentage` on live trades.

**Steps To Reproduce**
Here are the steps to reproduce the issue:
1. Close/exit any running Hummingbot instance.
2. Edit `conf_fee_overrides.yml` under `conf` folder, and setting the value for maker fee and taker fee.
   With the following as an example:
   binance_maker_fee: 0.05
   binance_taker_fee: 0.05
4. Save the changes and start your Hummingbot.
5. Import a strategy using `import` command.
    With the following as an example:
    Pair: COTI-BTC 
    Exchange: Binance
    Strategy: PMM
6. Run the strategy using the `start` command. Notice that the fee percentage on the trades made is not the ones that been set on conf_fee_overrides.yml.

**Screenshots**
![004](https://user-images.githubusercontent.com/12313129/87929188-3aeeba00-cab0-11ea-918b-1c2f50c1f5db.png)

**Release version**
Windows Binary, Version 0.29.0

**Attachments**
[logs_conf_pure_mm_COTIBTC.log](https://github.com/CoinAlpha/hummingbot/files/4947152/logs_conf_pure_mm_COTIBTC.log)

**Optional: your discord username:**
sigit#7187

**Comment by dennisocana** [comment] 2020-07-21 06:02
Looks like this is isolated to Binance. Screenshot below shows live trades in KuCoin (v0.29.0) with the maker fee overridden to 0.25 although I haven't tried yet with the rest of connectors.

![image](https://user-images.githubusercontent.com/50150287/88018065-8a3cf500-cb59-11ea-8305-32eb288e35cf.png)

Also see failing unit test in Jenkins for `test_fee_overrides_config` that may be related.

```
======================================================================
FAIL: test_fee_overrides_config (test.integration.test_binance_market.BinanceMarketUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dennis/hummingbot/test/integration/test_binance_market.py", line 227, in test_fee_overrides_config
    self.assertAlmostEqual(Decimal("0.005"), l_maker_fee.percent)
AssertionError: Decimal('0.005') != Decimal('0.002') within 7 places (Decimal('0.003') difference)
```

**Comment by cryptogasm** [comment] 2020-07-21 07:08
@sigit2306 according to this https://www.binance.com/en/fee/schedule you are VIP6 and VIP8 is that correct? I think you get 0.001 because hummingbot do decimal and by default its 0.1% and it detect that you do not have that 0.05% fee discount on binance but if you check on your binance account the fee is different if you are really a VIP6 VIP8.

**Comment by sigit2306** [comment] 2020-07-27 05:01
Yes @cryptogasm you're right, checking exchange account shows fee is different from hummingbot fee.

JackShiloh#0590 also having this issue on kuCoin live trades, he has 0% maker fees on kuCoin and was running 5 bots (docker build) with a separate folder and configuration for each bot.

bot honoring `conf_fee_override.yml` so this instance is calculating correctly
![kucoin_hb_bot1history](https://user-images.githubusercontent.com/12313129/88504513-36ba2380-cfff-11ea-9b92-3775e1724459.png)

bot not honoring `conf_fee_override.yml` 
![kucoin_hb_bot2history](https://user-images.githubusercontent.com/12313129/88504814-f7d89d80-cfff-11ea-938f-5370217a1355.png)

The user confirmed that on kuCoin account, trade reflects 0% maker fee.

**Comment by vic-en** [comment] 2020-08-13 17:42
Just looked at the code and made real trade, override fee works.
<img width="960" alt="works" src="https://user-images.githubusercontent.com/31972210/90166679-897f3380-dd92-11ea-82a3-e6f08babafbb.PNG">

Note: The fee column is remove from the output of history command as of v0.30. However, there's a CSV file for each strategy in the data directory which can be checked to confirm fees.

Kindly update with exact steps to reproduce (**if bug's still present**).

**Comment by rxlxrxsx** [comment] 2020-08-14 11:00
Confirmed fee override works on ``v-0.30.0`` based on trade produced on Binance. I configured the fee to 0.2% on my ``conf_fee_overrides.yml`` file.

![image](https://user-images.githubusercontent.com/64377055/90240900-aa13c000-de5c-11ea-9269-da390b2dfbb2.png)

**Comment by vic-en** [comment] 2020-08-17 14:54
Closing since issue not present/re-producable in dev branch.

**Closed by vic-en** 2020-08-17 14:54 UTC
Labels: binance, bug, in-progress
