### ISSUE TITLE
New `spread` command to configure ask and bid simultaneously

### ISSUE THREAD

**Issue by agarzon** [CoinAlpha/hummingbot#2928] opened 2021-02-07 19:53 UTC
**Feature Suggestion**

To include a new command called maybe just `spread` which automatically set up **ask and bid spreads using the same value.** So instead of run `ask_spread 1.2` and then `bid_spread 1.2` I could just run `spread 1.2` and have the same result.

**Impact**
It will save a lot of time reconfiguring the bot manually, which happens several times a day.

**Comment by krisj** [comment] 2021-02-20 17:43
duplicate of #1698 - see why it was closed. I suggest adding wider context and use cases for reconsideration perhaps?

**Comment by dennisocana** [comment] 2021-06-03 03:13
Will be available starting from version 0.40 release.

**Closed by dennisocana** 2021-06-03 03:13 UTC
Labels: new feature
