### ISSUE TITLE
Uniswap Connector - WETH and ETH pairs are missing

### ISSUE THREAD

**Issue by stokak** [CoinAlpha/hummingbot#3086] opened 2021-03-16 06:13 UTC
**Issue**
Many pairs are missing from the uniswap connector. For example the most common such as WETH-WBTC, WETH-DAI...

**Steps to reproduce**
Simply start instance of hummingbot, create amm_arb strategy, select uniswap as first connector and input the desired pair. The pairs do not show in the dropdown list.

**Release version**
0.37.1

**Comment by RC-13** [comment] 2021-03-17 03:50
@stokak Thanks for opening a ticket. This issue was caused by the previous `ethereum_token_list_url` that we are using, the old one is down and currently using https://defi.cmc.eth.link/ as an alternative to prevent the bot from freezing, though that URL currently doesn't support other tokens including `WETH`. As a workaround, you can replace the `ethereum_token_list_url` to https://uniswap.mycryptoapi.com/ while our team is looking for a better alternative for the token list.

**Comment by stokak** [comment] 2021-03-17 06:58
Thank you @RC-13!

**Comment by dennisocana** [comment] 2021-03-25 13:28
Closing related to https://github.com/CoinAlpha/hummingbot/issues/3055

**Closed by dennisocana** 2021-03-25 13:28 UTC
Labels: P1
