### ISSUE TITLE
[BUG] [dev/0.7.0]fatal error: cpp/PyRef.h: No such file or directory is displayed during compilation

### ISSUE THREAD

**Issue by sazed5055** [CoinAlpha/hummingbot#249] opened 2019-05-17 22:12 UTC
**Describe the bug**
// [BUG] [dev/0.7.0] fatal error: cpp/PyRef.h: No such file or directory is displayed during compilation
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Delete the existing local repo  rm -rf hummingbot
2. Clone repo git clone https://github.com/CoinAlpha/hummingbot.git
3. git checkout dev/0.7.0 to switch to the latest dev branch
4. ./install (successful)
5. Activate environment conda activate hummingbot (successful)
6. compile
7. Error displayed fatal error: cpp/PyRef.h: No such file or directory

**Screenshots**

![1](https://user-images.githubusercontent.com/50499987/57958795-6e93ea00-78d7-11e9-97e7-8d6581ddccba.jpg)

**version**
Dev/0.7.0

**Comment by mifeng** [comment] 2019-06-11 23:33
We will try to reproduce.

**Comment by vivianrc** [comment] 2019-06-12 17:13
@sazed5055 thanks for the detailed report! We couldn't reproduce the bug -- could you try again with the latest new builds? Let us know if there are any more problems.

**Comment by nkona** [comment] 2019-06-21 21:58
Bug appears to have been fixed in later releases. Will close issue for now, please reopen if the same bug continues to appear.

**Closed by nkona** 2019-06-21 21:58 UTC
Labels: bug
