### ISSUE TITLE
[BUG] Arbitrage strategy: object has no attribute 'c_find_profitable_arbitrage_orders'

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#187] opened 2019-05-07 23:25 UTC
**Describe the bug**

After about 1.5 hrs of running the arbitrage strategy, the follow message appeared and persisted for hours until restarting the bot:

```
2019-05-08 00:12:17,008 - wings.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "wings/clock.pyx", line 95, in wings.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 272, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
    self.c_process_market_pair(market_pair)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 390, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
    self.c_process_market_pair_inner(
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 507, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
    profitable_orders = self.c_find_profitable_arbitrage_orders(self._min_profitability,
AttributeError: 'hummingbot.strategy.arbitrage.arbitrage.ArbitrageS' object has no attribute 'c_find_profitable_arbitrage_orders'
```

There were no other errors in the log file apart from this repeated one, every minute.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: `arbitrage`: `binance` + `ddex`

**Screenshots**
N/A

**Release version**
dev.0.6.0, pulled overnight Monday / morning Tuesday Pacific time.

**Attachments**
N/A

**Comment by Steve1943** [comment] 2019-05-08 03:02
See attached - Also current dev-0.6.0.  
NB this was RadarRelay/Binance so the problem is unlikely DEX exchange specific.  

[AttributeError_object_has_no_attribute.txt](https://github.com/CoinAlpha/hummingbot/files/3155262/AttributeError_object_has_no_attribute.txt)

**Comment by yzhang1994** [comment] 2019-05-09 17:10
@carlolm @Steve1943  I believe this bug has been fixed in the past 2 days as we made changes to the ArbitrageStrategy.pyx file. The line of code where the error appeared no longer exists in our code base. Please let us know if you are still seeing this in the latest version.

**Closed** 2019-05-09 18:01 UTC
Labels: bug
