### ISSUE TITLE
KuCoin - Error connecting API keys

### ISSUE THREAD

**Issue by stayhungry7** [CoinAlpha/hummingbot#2968] opened 2021-02-19 05:32 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
After installation, i tried to create a connect for kucoin.
typed API key, secret and passphrase
Then i got an error message.
Error fetching data from https://api.kucoin.com/api/v1/accounts?type=trade

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. connect kucoin
2. type key,secret and passphrase

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/37467951/108462026-39dc7000-72bf-11eb-8d7e-86d09371cf02.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment] 2021-02-19 05:51
Hi @stayhungry7, this HTTP 401 status error that you encountered means that your API key is either `Unauthorized` or an `Invalid API Key`. Try re-adding your API keys by doing `connect kucoin` again and make sure that they are copied and pasted properly, you can check this guide on[ how to copy and paste API keys on Hummingbot](https://hummingbot.zendesk.com/hc/en-us/articles/900004871203-Copy-and-paste-your-API-keys). Also, make sure that your API key is trade enabled and your IP is added on the whitelist if you ticked `IP white list`,
![image](https://user-images.githubusercontent.com/57189990/108462862-5032fd80-72b8-11eb-882f-568c8c09c468.png)

**Comment by krisj** [comment] 2021-02-20 16:44
> Hi @stayhungry7, this HTTP 401 status error that you encountered means that your API key is either `Unauthorized` or an `Invalid API Key`. Try re-adding your API keys by doing `connect kucoin` again and make sure that they are copied and pasted properly, you can check this guide on[ how to copy and paste API keys on Hummingbot](https://hummingbot.zendesk.com/hc/en-us/articles/900004871203-Copy-and-paste-your-API-keys). Also, make sure that your API key is trade enabled and your IP is added on the whitelist if you ticked `IP white list`,
> ![image](https://user-images.githubusercontent.com/57189990/108462862-5032fd80-72b8-11eb-882f-568c8c09c468.png)

I wonder if it would be a good ROI to implement some human readable error code handling routines in connectors? potential support time saving?

**Comment by dennisocana** [comment] 2021-02-22 03:53
Closing since this is not a bug

**Closed by dennisocana** 2021-02-22 03:53 UTC
Labels: bug
