### ISSUE TITLE
[BUG] Installation issues when using Source on Cloud server

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2564] opened 2020-11-05 17:26 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
When trying to install HB using source on Cloud server. Steps provided on both manual and script followed until "./install" returning error,

_Could not find conda environment: hummingbot
You can list all discoverable environments with `conda info --envs`._

Next step was to use "conda activate hummingbot", returning error, 

_conda environments:
base                  *  /home/ubuntu/test/home/ubuntu/test_

Tried to install HB using source (scripts) on local machine and seems to be working ok.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1) Open Cloud server and download install script via
	_wget https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/install-from-source/install-source-ubuntu.sh_

2) Enable script permissions
	_chmod a+x install-source-ubuntu.sh_

3) Run installation
_./install-source-ubuntu.sh_

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![1](https://user-images.githubusercontent.com/73840223/98274334-410c9600-1fce-11eb-8f72-13a56b1d0565.PNG)

![image](https://user-images.githubusercontent.com/73840223/98275645-d2c8d300-1fcf-11eb-9efe-cd3f7a160209.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.32.0

**Comment by RC-13** [comment] 2021-01-13 06:31
Closing case for now, steps worked when switched to t2.small instance

**Closed by RC-13** 2021-01-13 06:31 UTC
Labels: bug

**Comment by taina0407** [comment] 2021-09-28 10:35
Just got the same error today. Seem like this caused by memory is not enough. For anyone facing the same issue, the temporary solution is to enable SWAP (2GB swap as least), or switch to a large VPS
