### ISSUE TITLE
[BUG] Bot creating many transaction errors when making a market on Radar Relay

### ISSUE THREAD

**Issue by mgeale** [CoinAlpha/hummingbot#152] opened 2019-04-29 23:17 UTC
**Describe the bug**
Running the bot results in many transaction errors on Ethereum.
https://etherscan.io/address/0xefb722c5960c37e5f20295012f274a56625e1912

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...

```########################################################
###   Cross exchange market making strategy config   ###
########################################################

# The following configuations are only required for the
# cross exchange market making strategy

# Exchange and token parameters
maker_market: radar_relay
taker_market: ddex
maker_market_symbol: BAT-WETH
taker_market_symbol: BAT-WETH

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.005

# Maximum order size in terms of quote currency
trade_size_override: 0.0

# Maximum aggregate amount of orders in quote currency
# that are allowed at a better price than Hummingbot's
# order before Hummingbot adjusts its order and pricing
top_depth_tolerance:

- - ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 1000
- - ^.+ETH$
  - 10
- - ^.+BTC$
  - 0.5
# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: false

# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.0

# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0
```
2. Start the bot using this command: ...
Run bot as per Hummingbot document

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.4.0

**Attachments**
Example warning from log file:
```wings.wallet.web3_wallet_backend - WARNING - The transaction 0xf9cb1e6c728f6895df09ec803c7b7003d52c0fd46dd18a71bf4e26ec39e52a0c has failed.```

// NOTE: We understand If you do not want to publish your config/log files. You can instead send them privately to dev@coinalpha.com and drop a link of this issue in the email.
// WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

**Comment by martinkou** [comment] 2019-04-30 00:58
@chowryan please take a look

**Comment by chowryan** [comment] 2019-04-30 05:05
this looks like the cancel bug we saw in 0.4.0. are you running from source? the bot is trying to cancel a lot https://explain.0x.org/?networkId=1&tx=0x45ad3303c2e1c6b47eba918b5ef62827f8cfc9b0fb8fda2ecec83205aba9ad9c

for radar relay you should disable active order cancelling in the yml strategy file.

**Comment by chowryan** [comment] 2019-04-30 05:06
try updating to 0.5.0

**Comment by mgeale** [comment] 2019-04-30 06:03
i'm running with docker. I updated to 0.5.0. There are errors still happening but maybe not as many as before.
https://etherscan.io/address/0xefb722c5960c37e5f20295012f274a56625e1912

I have ```active_order_canceling: false``` but orders are being cancelled. What's the correct config?

Thanks

**Comment by chowryan** [comment] 2019-04-30 16:02
sorry didnt see your config earlier, change cancel order threshold to prevent radar from cancelling too aggressively

```cancel_order_threshold: -1.0```

**Comment by mgeale** [comment] 2019-05-01 09:03
Great, thanks. I've updated to 0.5.0, adjusted the cancel order threshold and no more transaction errors

**Comment by chowryan** [comment] 2019-05-01 17:24
cool! seems like the problem is fixed, closing this issue.

**Closed by chowryan** 2019-05-01 17:24 UTC
Labels: bug
