### ISSUE TITLE
[BUG] Error running performance analysis 

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1376] opened 2020-02-01 21:33 UTC
**Describe the bug**
// Running a `history` command shows a performance analysis error
This is related to https://github.com/CoinAlpha/hummingbot/issues/1289

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 2

# The following configurations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: binance
secondary_market: huobi
primary_market_trading_pair: XZC-BTC
secondary_market_trading_pair: XZC-BTC

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.001

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters
```
Error logs 
```
2020-02-01 11:34:20,804 - 11284 - hummingbot.core.utils.exchange_rate_conversion - ERROR - None is not in one of the data feeds: dict_keys(['coincap_api', 'coin_gecko_api']).
2020-02-01 11:34:20,804 - 11284 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: Data feed name not valid.
Traceback (most recent call last):
  File "hummingbot\core\utils\kill_switch.py", line 38, in check_profitability_loop
  File "hummingbot\client\command\history_command.py", line 102, in calculate_profitability
  File "hummingbot\client\command\history_command.py", line 89, in _calculate_trade_performance
  File "hummingbot\client\performance_analysis.py", line 245, in calculate_trade_performance
  File "hummingbot\core\utils\exchange_rate_conversion.py", line 178, in convert_token_value_decimal
  File "hummingbot\core\utils\exchange_rate_conversion.py", line 195, in convert_token_value
  File "hummingbot\core\utils\exchange_rate_conversion.py", line 132, in get_exchange_rate
Exception: Data feed name not valid.
```
**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/73598998-d98c5c00-450c-11ea-9ec9-640ee5a183f2.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
version 0.22.0 using the Windows binary

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Adriano Ecker#8145
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment] 2020-02-04 03:24
Was able to reproduce behavior using windows binary / docker test aws - master 0.23.0

history command triggers the error

docker test aws / paper-trade off / binance / zil-eth
![image](https://user-images.githubusercontent.com/55869559/73711071-ae8a4e00-4740-11ea-985e-d794fe95da7d.png)

```
2020-02-04 03:15:13,783 - 10 - hummingbot.client.hummingbot_application - ERROR - Unexpected error running performance analysis.
Traceback (most recent call last):                                                                                              
  File "/hummingbot/client/command/history_command.py", line 131, in trade_performance_report                                   
    inventory_df: pd.DataFrame = self.balance_comparison_data_frame(market_trading_pair_stats)                                  
  File "/hummingbot/client/command/history_command.py", line 68, in balance_comparison_data_frame                               
    starting_balance = self.starting_balances.get(asset).get(market.name)                                                       
AttributeError: 'NoneType' object has no attribute 'get' 
```


windows binary / paper-trade on / coinbase-pro / link-eth
https://media.discordapp.net/attachments/625626777506545674/674048701253287937/unknown.png?width=864&height=469

```
2020-02-04 08:28:41,472 - 11104 - hummingbot.client.hummingbot_application - ERROR - Unexpected error running performance analysis.
Traceback (most recent call last):
  File "hummingbot\client\command\history_command.py", line 131, in trade_performance_report
  File "hummingbot\client\command\history_command.py", line 74, in balance_comparison_data_frame
TypeError: unsupported operand type(s) for -: 'decimal.Decimal' and 'float'
```

**Comment by Nullably** [comment] 2020-02-10 11:12
I cannot reproduce this error at all, i have tried arbitrate strategy on binance vs huobi. I tried switching between paper trading mode and real mode.
@Hashira-Lars @rennel-tabing Can you please confirm if this is still an issue on the current development? thanks.

**Comment by Hashira-Lars** [comment] 2020-02-11 03:52
@Nullably Can you try my config i have reproduce it running for 30mins

1. enable paper-trade first 
2. create new strategy using the configs below
3. run the bot / (optional wait for trade to be filled)
4. enter history command


![image](https://user-images.githubusercontent.com/55869559/74209907-a4c69480-4cc4-11ea-9c34-15fa1d2bc6ba.png)


![image](https://user-images.githubusercontent.com/55869559/74209892-9bd5c300-4cc4-11ea-90b5-916fe8762341.png)

Branch : latest dev image

**Comment by Nullably** [comment] 2020-02-19 05:53
@Hashira-Lars 
The fix for the last error is on this PR 
https://github.com/CoinAlpha/hummingbot/pull/1434
Once it's merged, you can test it on development, thanks.

**Closed** 2020-03-02 22:16 UTC
Labels: bug, master
