### ISSUE TITLE
Increasing order amount 

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2834] opened 2021-01-12 06:03 UTC
**Describe the bug**
- Sudden increase on orders amount (some are very large orders)
- Happens on binance futures both live and testnet

**Steps To Reproduce**
- From this configuration the expected largest order amount is 2.4 LTC
![image](https://user-images.githubusercontent.com/54516858/104272934-275d6280-54d9-11eb-9a00-fa8255d110f6.png)

**Screenshots**
- Some of the trades
![image](https://user-images.githubusercontent.com/54516858/104274588-27ab2d00-54dc-11eb-9072-da00d98eb448.png)
![image](https://user-images.githubusercontent.com/54516858/104275989-e36d5c00-54de-11eb-95f7-f8c703852d1a.png)
![image](https://user-images.githubusercontent.com/54516858/104275816-8e314a80-54de-11eb-98ad-046753401769.png)

**Release version**
- 0.34.0 / 0.35.0

**Attachments**
- exported trades
[testnetperp_csv.txt](https://github.com/CoinAlpha/hummingbot/files/5799986/testnetperp_csv.txt)
 - zip 3 day logs
[perp.zip](https://github.com/CoinAlpha/hummingbot/files/5799992/perp.zip)

**Comment by PtrckM** [comment] 2021-01-15 06:40
- tried current development from https://github.com/CoinAlpha/hummingbot/pull/2787
```
                "branch": "development",
                "commit": "61febbd1b70bc69c864df5b71ab8fbd82c6dbf5c",
                "date": "2021-01-12T17:37:55Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```
- with strategy configuration
![image](https://user-images.githubusercontent.com/54516858/104690410-596ffe00-573f-11eb-9801-91574f9fe6bf.png)
- bot still increase order amount
![image](https://user-images.githubusercontent.com/54516858/104690470-7278af00-573f-11eb-81f3-bf2c8cf2b69b.png)
- exported csv
 
[newdev_csv.log](https://github.com/CoinAlpha/hummingbot/files/5818867/newdev_csv.log)

**Comment by krisj** [comment] 2021-01-15 18:11
> * From this configuration the expected largest order amount is 2.4 LTC

are you deducting it from 0.12 (order_amount) * 20 (leverage)? If so - it is not how it works. The order_amount is what is submitted to the exchange. Leverage only affects the margin requirement on your account, not the order amount the bot would submit.

Those larger orders just seem to be the position management closing the positions... is that not the case?

Having said that - I've only been testing the Hedged mode so far.

**Comment by vic-en** [comment] 2021-02-08 15:23
@krisj is right. Those orders with excessive amounts are as a result of the position management feature trying to close the accumulated position/contract size opened by all 20 order levels.
This is absolutely not a bug.

**Closed by vic-en** 2021-02-08 15:23 UTC
Labels: P2, binance futures, binance futures testnet, bug
