### ISSUE TITLE
Hanging orders with PMM do not hang.

### ISSUE THREAD

**Issue by al3xclarke** [CoinAlpha/hummingbot#3836] opened 2021-07-31 21:40 UTC
**Describe the bug**

Running the PMM strategy hanging orders will be cancelled at the order_refresh_time.

**Steps To Reproduce**

1. Create a new PMM strategy.
1. Set a low (0.01) bid_spread and ask_spread.
1. Set a low (0.0005) order_amount.
1. Set order_refresh_time to 5.
1. Set filled_order_delay to 1.
1. Set hanging_orders_enabled to Yes.

Start the bot and watch it cancel the hanging orders after 5 seconds.

The above values are ones I've been using for testing and are not the cause of the bug - you can use any values so long as hanging_orders_enabled is set to Yes.

**Release version**

0.41.0

Discord: al3xclarke

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramunu) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment] 2021-08-02 04:56
Hi @al3xclarke Could you please attach your config and log file?

**Comment by gerald-hb** [comment] 2021-08-02 05:09
Hello @al3xclarke. I got a different results
![image](https://user-images.githubusercontent.com/84826167/127806992-81ddde17-a9ff-475a-9cad-448d1ac03e7a.png)
![image](https://user-images.githubusercontent.com/84826167/127807019-b4c0db4b-dc8a-4dcd-8261-8147ee87f2e0.png)
Please attach your config and logs so we can take a further look into this.

**Comment by nikspz** [comment] 2021-08-02 06:06
You could face this issue because of insufficient balance of one asset.
I tried with balance on both, base and quote and looks like okay for FRONT-USDT

**Comment by al3xclarke** [comment] 2021-08-02 21:15
Thanks for the replies.

The issue was, in fact, insufficient balance of the assets! Lowering the order_amount value resolved this.

However, if the bot places lots of orders and depletes the available balance then the most recent orders placed suffer from this issue (as their value is below order_amount).

Is this not a bug?

**Comment by glenntomas** [comment] 2021-08-02 22:33
@al3xclarke Hi! As far as i know that's not a bug. The bot uses the remaining balance that you have to create an order.

**Comment by al3xclarke** [comment] 2021-08-04 19:25
Ok, thanks for confirming.

I've just submitted a feature request, that would solve my issue, here (https://github.com/CoinAlpha/hummingbot/issues/3854).

**Comment by dennisocana** [comment] 2021-08-04 23:18
@al3xclarke I'd like to understand more about the feature request you opened. By default, when using pure market making strategy, your orders are created exactly based on your `order_amount` value. The amount will only be adjusted if you have inventory skew enabled.

Your Github issue's description doesn't connect. What behavior are you trying to achieve from your bot? And can you send us your config file especially the logs as the support guys have requested?

**Comment by RC-13** [comment] 2021-11-29 02:13
Closing ticket. Ticket has been idle for a while and confirmed that there is no issue with hanging order.

**Closed by RC-13** 2021-11-29 02:13 UTC
Labels: bug
