### ISSUE TITLE
minimum_spread trouble

### ISSUE THREAD

**Issue by drumer979** [CoinAlpha/hummingbot#2984] opened 2021-02-23 10:09 UTC
Problem:

config (part of it):

bid_spread: 1
ask_spread: 1
minimum_spread: 0.7

if position is closed by minimum_spread, than new position open in xxxx time. This is only happening in windows installation. On linux new position is open in next 1sec, but in binary windows version it takes random time from 10sec to 3minutes.

**Release version**
// 0.36 windows binary

**Comment by rapcmia** [comment] 2021-02-24 01:24
Hi @drumer979 can you share a screenshot of your config? I'd like to see how this happens on testbots. Thank you

**Comment by dennisocana** [comment] 2021-02-25 00:49
@rapcmia I think the user is saying that normally, when an order's spread dips below the `minimum_spread` value, it cancels the order and creates a new one right away. But in his case, there's a delay on binary version of Windows.

Try to reproduce the behavior with the scenario above. I suspect his issue is also caused by a network problem.

**Comment by rapcmia** [comment] 2021-02-28 01:30
Hi @drumer979 

I tried to test this on my Binary build v36 and I am getting the same behavior with 10-15secs interval when the order is cancel due to `mininum_spread` and created again. This happens as well with my raspberry pi docker build too which shares the same connection so I think you may want to consider your current network connection. 

![image](https://user-images.githubusercontent.com/73840223/109405056-56576700-79a7-11eb-930a-579677376a89.png)

**Comment by drumer979** [comment] 2021-03-05 08:50
right now Im using liquidity mining strategy and Im wainting for 0.37. Will "minimum_spread" be included in this version?

**Comment by rapcmia** [comment] 2021-04-08 11:23
The `minimum_spread` parameter is still not available for the liquidity_mining strategy. Since this is still on BETA, we expect more features to be added in future releases. You may want to update your Hummingbot as well to version 0.38.0

**Comment by RC-13** [comment] 2021-04-12 03:13
Closing ticket, feel free to open if issue re-occur.

**Closed by RC-13** 2021-04-12 03:13 UTC
