### ISSUE TITLE
Command "config telegram_token" converts value to lowercase letters

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2726] opened 2020-12-15 09:18 UTC
**Describe the bug**
We have been trying to test how we can work user's telegram back to client. Whenever user starts the bot, it returns a deprecation warning on old handler API then stops at a unhandled error in background.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
- Start the bot
- Telegram error occurs

![image](https://user-images.githubusercontent.com/73840223/102194298-18928880-3ef8-11eb-9970-1a229ef75c85.png)

Logs:
2020-12-11 22:57:25,679 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Unauthorized
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 78, in start_check
    self._initialize_notifiers()
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 268, in _initialize_notifiers
    notifier.start()
  File "/home/hummingbot/hummingbot/notifier/telegram_notifier.py", line 99, in start
    self._updater.start_polling(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/ext/updater.py", line 258, in start_polling
    self.job_queue.start()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/ext/jobqueue.py", line 311, in start
    name="Bot:{}:job_queue".format(self._dispatcher.bot.id))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/bot.py", line 54, in decorator
    self.get_me()
  File "<decorator-gen-1>", line 2, in get_me
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/bot.py", line 251, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/utils/request.py", line 277, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/telegram/utils/request.py", line 243, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

Steps taken:
- When the error occur, User have relaunch the bot so this would work again but Telegram will not work
- Tried to reinstall the bot from user's VPS, same issue
- Tried to make sure it has the correct Token and Chat ID? Yes but no joy.
- Tried to create new instance and new telegram bot, no joy and same error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73840223/102195261-4cba7900-3ef9-11eb-9e8c-373c487bbb22.png)

**Release version**
0.33.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_strax-btc (1).log](https://github.com/CoinAlpha/hummingbot/files/5694623/logs_strax-btc.1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
cm

**Comment by bonez56** [comment] 2020-12-22 08:01
I believe I know what the issue is here, as I ran into the same problem.

If you paste the Telegram token into the Hummingbot interface using 'config telegram_token', when it writes the token to conf_global.yml in the background, it changes the whole token to lowercase.

For example a token ABcDeFGhI becomes abcdefghi when it's written to the config file.

If you edit conf_global.yml yourself and paste the token in, it retains it's case and Hummingbot is able to connect to the Telegram API without any issues.

**Comment by RC-13** [comment] 2020-12-23 09:25
Closing this case for now since we have a workaround for this problem, feel free to re-open case if workaround no longer works.

**Comment by RC-13** [comment] 2020-12-23 09:48
closing case in favor of this same issue #2391

**Closed** 2020-12-23 09:48 UTC
Labels: P2, bug
