### ISSUE TITLE
[BUG] bot stops working, order_amount parameter 'disappeared' after restart container, in the config suddenly set to None

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2599] opened 2020-11-10 15:41 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
The order_amount parameter 'disappeared', in the config suddenly set to None.

Bot was running fine for about 2 days, then half an hour ago it just stopped working.
When I restarted the docker container, it did not start because the order_amount was missing and when outputting the config the parameter was None.

I have seen this happen 3 times before on other instances, I run a few dozen HB bots.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Default setup of the config, order_amount a bit above the minimum required
2. Inventory_skew enabled (default 50% and 1x)
3. Multiple order_levels set but not sure if this has anything to do with the issue

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.32.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by zappra** [comment] 2020-11-10 16:07
I've had this, or similar. Sounds like your minimum order amount became invalid due to a change in price, and as a result the bot silently stopped trading. When you restarted, the (now) invalid parameter was set to none. I think this latter part is intended behaviour, I've had similar issues eg. when starting a bot with a script path set but the script file is missing. This "parameter missing" thing happens quite a lot when copying configs around, eg. from a VPS bot to local environment for debugging.

**Comment by zappra** [comment] 2020-11-10 16:12
Issue #2372

**Comment by TradeClaw** [comment] 2020-11-11 21:08
Yeah, sounds about right, I noticed it was after a little dump of the token value and it doesn't happen on BTC on Binance since the required minimum 0.0011 is 10x what is required, so it will only happen on the actual $10-ish min order size bots.

**Comment by TradeClaw** [comment] 2020-11-12 12:58
It just happened again on HARD-USDT, it has to do with the minimum order amount.
I noticed coz my container's memory usage dropped from the usual 500MB to 150MB so I guess some threads crashed.
Bot was doing nothing for about 10 hours.

1. Stop/start command changes nothing, no movement (not restarting container, just in console)
2. Running config still shows the order_amount set at the start of the bot (20 HARD)
...after restarting the container, the order_amount in the config appeared as None.

When reconfiguring the order_amount it showed I had to use about 25 HARD, so it clearly happens when it encounters a failure in minimum order size when the value of the token dumps.

**Comment by RC-13** [comment] 2020-12-17 04:43
Hi, this is currently an expected behavior that happens when there is change in the market price and the current set order_amount is no longer meeting the exchange minimum. The value `None` appears whenever you restart your container or Hummingbot and import your strategy since bot re-calculate the suggested order amount and recognize it as below the suggested amount. While if the strategy is currently running, no orders will be created until the market price goes back to original. I will be closing this case for now, feel free to open a new feature request ticket that you think can address this behavior

**Closed by RC-13** 2020-12-17 04:43 UTC
Labels: bug
