### ISSUE TITLE
Ascendex - typo/misprint on the logs of warning about notional amount in XEMM strategy

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#3438] opened 2021-05-25 10:30 UTC
**Describe the bug**
While checking the Cross Exchange Market-Making strategy for AscendEx connector, I noticed there is a cosmetic bug on the logs `Notional amount 3.4429700 is not withing the range of 5-400000.`

![image](https://user-images.githubusercontent.com/73840223/119478714-9ea5db80-bd82-11eb-9911-85c0be5f1c48.png)

```
2021-05-25 09:44:22,003 - 1 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Notional amount 3.4429700 is not withing the range of 5-400000.
2021-05-25 09:44:22,009 - 1 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Error submitting SELL LIMIT_MAKER order to AscendEx for 1 DOGE-USDT 0.3512376.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 497, in _create_order
    raise ValueError(f"Notional amount {notional} is not withing the range of {ascend_ex_trading_rule.minNotional}-{ascend_ex_trading_rule.maxNotional}.")
ValueError: Notional amount 0.3512376 is not withing the range of 5-400000.
```

**Steps To Reproduce**
1. Create a simple Cross Exchange Market-Making strategy 
2. Primary: Ascendex, Secondary: KuCoin, Markets: DOGE-USDT
3. Start the bot

**Release version**
dev-0.40.0

**Attachments**
[logs_xemm-ascendex.log](https://github.com/CoinAlpha/hummingbot/files/6538515/logs_xemm-ascendex.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by dennisocana** [comment] 2021-06-01 09:33
This was caused by the connector's order book mismatch with the exchange as mentioned in https://github.com/CoinAlpha/hummingbot/issues/3164.

Fixed in version 0.40 release.

**Closed by dennisocana** 2021-06-01 09:33 UTC
Labels: P3
