### ISSUE TITLE
perpetual_market_making strategy not submitting any order on binance and bybit when started

### ISSUE THREAD

**Issue by fab-ioc** [CoinAlpha/hummingbot#4820] opened 2021-11-27 16:39 UTC
**Describe the bug**
Using a fresh build of hummingbot master branch on Ubuntu 20.04.3 LTS
perpertual_market_making with pretty standard configuration 1% spread, size 0.0001,  TP 0.05%, SL 0.1%, refresh 30 sec, on BTC-USDT, on both bybit_perpetual and binance_perpertual
does not submit any order after connection to exchange is established but just goes idle.

**Steps To Reproduce**
1. follow the documentation to build from source on linux
2. connect binance_perpetual
3. create perpetual_market_making
4. start

**Screenshots**
![image](https://user-images.githubusercontent.com/22630145/143689517-9cb3ce9f-6fa7-4f12-b57c-20ea5842ddda.png)

![image](https://user-images.githubusercontent.com/22630145/143689465-75018d78-aa7a-430c-a1a2-63f5edd65321.png)

**Release version**
0.45.0

**your discord username:** **hanz#1697**

**Comment by rxlxrxsx** [comment] 2021-11-28 01:49
Hi @fab-ioc, please try to adjust your order_amount to .001. Both Binance and Bybit perpetual requires a minimum order size of .001 for the BTC-USDT pair.

https://www.bybit.com/data/basic/linear/contract-detail?symbol=BTCUSDT
https://www.binance.com/en/futures/trading-rules/perpetual

<img width="587" alt="Screen Shot 2021-11-28 at 9 46 15 AM" src="https://user-images.githubusercontent.com/64377055/143725846-80e4d996-de24-4aa0-b3ef-ac3d9c16381c.png">

**Comment by fab-ioc** [comment] 2021-11-28 07:39
ah right, thanks for pointing that out.
In that case, would it be neater to log some sort of warning when an attempt is made to submit an order with invalid size ?

**Comment by RC-13** [comment] 2021-11-28 23:27
@fab-ioc Thank you for the feedback, we have some warnings when submitting invalid size, this appears when the order amount is adjusted to a value that no longer allowed by the exchange. We also previously have a minimum order amount feature wherein the bot calculates the minimum order amount of the exchange using the quote balance and mid price, however our team decide to remove this since most of our users needs to set the value to 0 to remove this limit, see reference ticket #4421 . I'll be closing this ticket now since this is not a bug.

**Closed by RC-13** 2021-11-28 23:27 UTC
Labels: bug
