### ISSUE TITLE
[BUG] PMM on Radar Relay & IDEX: Can't connect to exchange and CoinGecko data feed is not working.

### ISSUE THREAD

**Issue by bghughes** [CoinAlpha/hummingbot#1463] opened 2020-02-25 22:29 UTC
**Describe the bug**
I have tried on both IDEX and radar relay to engage in PMM and have failed across the board. A key issue seems to be **"Coin Gecko API Request Failed. Unable to get prices."**

Additionally, when attempting to PMM on IDEX or Radar Relay, I get the following errors:
-Account balance error on IDEX (despite having >0.15ETH in both assets I am trying to PMM for)
-on Radar Relay:
Radar_relay market status:                                                                                       |
                    description  status                                                                               |
        order_books_initialized   False                                                                               |
                account_balance   False                                                                               |
      account_available_balance   False                                                                               |
       trading_rule_initialized   False                                                                               |
                 token_approval    True

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters:
config --->
PMM on IDEX or radar relay.
Default parameters for everything except allow bid-ask jumping and factor in transaction costs.
(local ETH node is correctly configured too)

2. Start the bot using this command: start

**Screenshots**
![image](https://user-images.githubusercontent.com/32072172/75293197-5698b180-57eb-11ea-92a2-a84643f80ff8.png)

**Release version**
0.23

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_pure_market_making_strategy_12.log](https://github.com/CoinAlpha/hummingbot/files/4252478/logs_conf_pure_market_making_strategy_12.log)
[logs_conf_pure_market_making_strategy_10.log](https://github.com/CoinAlpha/hummingbot/files/4252480/logs_conf_pure_market_making_strategy_10.log)
[logs_conf_pure_market_making_strategy_14.log](https://github.com/CoinAlpha/hummingbot/files/4252481/logs_conf_pure_market_making_strategy_14.log)

[Configs.zip](https://github.com/CoinAlpha/hummingbot/files/4252484/Configs.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** 0x1969dFc03B374D65a3f46D65FB3ca3F407FBd281

**Comment by Clint-G13** [comment] 2020-02-25 22:48
@bghughes the " coin gecko unable to get price " message is a known behavior. If order are being placed, this message can be ignored.
• For IDEX, you need to transfer balance to IDEX's dedicated wallet to allow trading (0.23.0) 
Note: On version 0.24.0 IDEX is no longer available
• as for Radar relay, on your current version its not working due to outdated version. Updated version is available on the latest stable build (0.24.0)

**Comment by dennisocana** [comment] 2020-02-28 10:48
IDEX connector has also been deprecated.
https://docs.hummingbot.io/release-notes/0.24.0/

**Comment by yzhang1994** [comment] 2020-03-02 22:21
@bghughes @dennisocana I believe this issue is a duplicate of https://github.com/CoinAlpha/hummingbot/issues/1469. Could you try to reproduce?

**Comment by dennisocana** [comment] 2020-03-04 00:08
@yzhang1994 yes this is a duplicate issue. Also, the IDEX connector is already deprecated and Radar Relay is not working for now.

**Closed by dennisocana** 2020-03-04 00:08 UTC
Labels: bug, duplicate
