### ISSUE TITLE
[BUG] Binance API code -4016 catch and set first acceptable order

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2574] opened 2020-11-08 13:26 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
The bot is not setting any orders when the price is out of reach (percentage gap too large).
But the API returns what the first acceptable price would be so HB could determine this way how to still set an order.
Not sure to call it a bug or an improvement.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Binance perpetual testnet has huge orderbook gaps, run it there with order optimization and this happens from time to time.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63117227/98466148-f9545d00-21cd-11eb-8080-2a65474cd88d.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
dev-0.33.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment] 2020-12-16 11:02
I think this can be requested as future enhancement since it's not a bug. As per Binance docs, it's due to big gap between the price and the current markup price (https://binance-docs.github.io/apidocs/futures/en/#40xx-filters-and-other-issues). Feel free to open a feature request for this matter. I'll be closing the ticket for now.

**Closed by RC-13** 2020-12-16 11:02 UTC
Labels: bug
