### ISSUE TITLE
[BUG] Hummingbot accepts trading pair typed in lowercase then produce error

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1230] opened 2019-12-21 00:24 UTC
**Describe the bug**
When testing a strategy and exchange, I accidentally entered a lowercase letter on the trading pair which was accepted by Hummingbot. After you start the bot, unknown error will occur.

**Steps To Reproduce**
create any strategy and user a lower case when entering trading pairs.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/57189990/71299873-140dbf80-23cb-11ea-857e-ac94857a00b2.PNG)
![Capture1](https://user-images.githubusercontent.com/57189990/71299874-15d78300-23cb-11ea-85f2-75baaae88859.PNG)

**Release version**

    Commit 6e1d988ebf38efe2baf1bb558d67ffcc8ba3b39c 
    branch: Development
    Date:   Fri Dec 20 13:16:12 2019

**Attachments**
[logs_conf_pure_market_making_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/3990811/logs_conf_pure_market_making_strategy_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by dennisocana** [comment] 2019-12-21 00:36
Taking out the trace dump from his logs to make this post searchable in case related bugs would come up in the future.
```
2019-12-21 07:58:06,012 - 6499 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 287, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
    orders_proposal = self.c_get_orders_proposal_for_market_info(
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 496, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
    pricing_proposal = self._pricing_delegate.c_get_order_price_proposal(self,
  File "hummingbot/strategy/pure_market_making/constant_spread_pricing_delegate.pyx", line 30, in hummingbot.strategy.pure_market_making.constant_spread_pricing_delegate.ConstantSpreadPricingDelegate.c_get_order_price_proposal
    object top_bid_price = market_info.get_price(False)
  File "/home/clinton_gogoc/hummingbot/hummingbot/strategy/market_trading_pair_tuple.py", line 36, in get_price
    return self.market.get_price(self.trading_pair, is_buy)
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 868, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket.get_price
    return self.c_get_price(trading_pair, is_buy)
  File "hummingbot/market/market_base.pyx", line 211, in hummingbot.market.market_base.MarketBase.c_get_price
    return self.c_quantize_order_price(trading_pair, top_price)
  File "hummingbot/market/market_base.pyx", line 186, in hummingbot.market.market_base.MarketBase.c_quantize_order_price
    price_quantum = self.c_get_order_price_quantum(trading_pair, price)
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 1004, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket.c_get_order_price_quantum
    TradingRule trading_rule = self._trading_rules[trading_pair]
KeyError: 'ZRX-WETh'
```

```
2019-12-21 07:58:06,054 - 6499 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 295, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
    filtered_proposal = self._filter_delegate.c_filter_orders_proposal(self,
  File "hummingbot/strategy/pure_market_making/pass_through_filter_delegate.pyx", line 22, in hummingbot.strategy.pure_market_making.pass_through_filter_delegate.PassThroughFilterDelegate.c_filter_orders_proposal
    int64_t actions = orders_proposal.actions
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Comment by BUDDHA-TONY** [comment] 2019-12-21 09:25
Tested with PMM - Binance/ZRX-ETH and have reproduce this error. Also tested in XEMM with binance.

![image](https://user-images.githubusercontent.com/55869559/71305992-10ebf100-2416-11ea-8504-2b2124c518bf.png)

list configs to check
![image](https://user-images.githubusercontent.com/55869559/71306009-2eb95600-2416-11ea-95ee-84cfaee5562b.png)

check external file to verify
![image](https://user-images.githubusercontent.com/55869559/71306037-74761e80-2416-11ea-9d5f-a76f762ac4a4.png)

                "branch": "development",
                "commit": "5a94dbb9d8876dd0ab2f5d166dd90193e0a25e72",
                "date": "2019-12-21T00:32:40Z",

**Comment by BUDDHA-TONY** [comment] 2019-12-24 04:15
issue with binance lower case ZRX-ETH token pair is [RESOLVE] https://github.com/CoinAlpha/hummingbot/pull/1236

**Comment by Clint-G13** [comment] 2019-12-26 23:06
Just re-tested the concern and verified that it is no longer showing, closing the ticket now.

**Comment by Clint-G13** [comment] 2020-01-01 20:16
Re-tested the issue using the master branch (0.21.0) and come up with a new issue under Radar relay market wherein balance is not detected properly as shown below:
![bal](https://user-images.githubusercontent.com/57189990/71645663-7abda200-2d16-11ea-8e1e-240204364a4a.PNG)

![Radar1](https://user-images.githubusercontent.com/57189990/71645479-1f8ab000-2d14-11ea-8a18-d92bc356a772.PNG)
***Note: Using uppercase for the market will work on the master branch.

Same result using the dev branch (0.22.0)
   
    commit 7f73abc040c894e6e87fdd887b5bc508bd6a910b
    Date:   Wed Jan 1 12:49:55 2020 

![Radar2-dev](https://user-images.githubusercontent.com/57189990/71645507-89a35500-2d14-11ea-9281-6955fb72b6bf.PNG)

      2020-01-02 03:35:05,475 - 6389 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
      Traceback (most recent call last):
      File 
     "/home/clinton_gogoc/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 107, in start
     asset_price_delegate = OrderBookAssetPriceDelegate(self.market_trading_pair_tuples[0])
     File "hummingbot/strategy/pure_market_making/order_book_asset_price_delegate.pyx", line 6, in hummingbot.strategy.pure_market_making.order_book_asset_price_delegate.OrderBookAssetPriceDelegate.__init__
     def __init__(self, market: MarketBase, trading_pair: str):
     TypeError: __init__() takes exactly 2 positional arguments (1 given)


    2020-01-02 03:36:54,716 - 6389 - root - ERROR - Unhandled error in background task: list.remove(x): x not in list
    Traceback (most recent call last):
      File "/home/clinton_gogoc/hummingbot/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
      File "/home/clinton_gogoc/hummingbot/hummingbot/client/command/stop_command.py", line 32, in stop_loop
    self.clock.remove_iterator(self.strategy)
      File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
    ValueError: list.remove(x): x not in list

**Comment by yzhang1994** [comment] 2020-01-10 22:50
@Clint-G13 Thanks for reporting. The Radar Relay connector is broken right now because Radar moved their API to a new version. We have not updated hummingbot's Radar connector which is probably why you are seeing all the issues on Radar. Tested this issue on Binance and Bamboo and they both seem to be working (no longer accepting invalid pairs). Closing this for now.

**Closed by yzhang1994** 2020-01-10 22:50 UTC
Labels: bug
