### ISSUE TITLE
Failed Test PR #294 - Unexpected error in user stream listener loop

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#309] opened 2023-02-03 02:01 UTC
**Describe the bug**
Getting these errors from to time while checking the long term bots running. Despite the error I don't see any impact on the orders affected. The same issue can be seen on the [Pro PR](https://github.com/CoinAlpha/hummingbot-professional/pull/259).

```python
2023-02-02 03:28:02,735 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No update found for order SIJUT5f3af2601b4c2646084410b53a05bafcea35284af1326
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 421, in get_order_status_update
    raise IOError(f"No update found for order {in_flight_order.client_order_id}")
OSError: No update found for order SIJUT5f3af2601b4c2646084410b53a05bafcea35284af1326
```

```python
2023-02-02 04:29:49,917 - 1 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 777, in _listen_to_account_balances_stream
    async for balance in stream:
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 2"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.111.67:443 {grpc_message:"Received RST_STREAM with error code 2", grpc_status:13, created_time:"2023-02-02T04:29:49.916969645+00:00"}"
>
```

**Steps To Reproduce**
1. Create and run a pure mm strategy using Injective
2. Observe the log pane, though the error may not appear immediately

**Attachments**
Logs and config: [userstream_oss.zip](https://github.com/CoinAlpha/hummingbot/files/10574886/userstream_oss.zip)

**Comment by RC-13** [comment] 2023-02-09 01:04
Closing the ticket since the PR has been submitted to foundation. Issue is confirmed a server side as well.

**Closed by RC-13** 2023-02-09 01:04 UTC
Labels: bug
